version: 2

sources:
  - name: land_registry # logical name
    schema: housing
    config:
      enabled: true
    loader: gcloud storage
    tables:
      - name: price_paid
        external:
          location: "gs://dezc-housing-processed/*"
          options:
            format: parquet
            hive_partition_uri_prefix: "gs://dezc-housing-processed/land_registry_price_paid/"
          partitions:
            - name: year
              data_type: int
